#pragma once

struct BASIC
{
    struct VTBASIC* pvtbasic;
    struct VTLO* pvtlo;
    struct VTALO* pvtalo;
    struct VTSO* pvtso;
    struct VTSHAPE* pvtshape;
    struct VTPNT* pvtpnt;
    struct VTPNTVEC* pvtpntvec;
    struct VTPNTSV* pvtpntsv;
    struct VTPNTS* pvtpnts;
    struct VTSCAN* pvtscan;
    struct VTXFM* pvtxfm;
    struct VTWARP* pvtwarp;
    struct VTEXIT* pvtexit;
    struct VTCAMERA* pvtcamera;
    struct VTLIGHT* pvtlight;
    struct VTPO* pvtpo;
    struct VTKEYHOLE* pvtkeyhole;
    struct VTWATER* pvtwater;
    struct VTTN* pvttn;
    struct VTBRK* pvtbrk;
    struct VTBRKP* pvtbrkp;
    struct VTBREAK* pvtbreak;
    struct VTFRAGILE* pvtfragile;
    struct VTZAPBREAK* pvtzapbreak;
    struct VTVOLBTN* pvtvolbtn;
    struct VTBUTTON* pvtbutton;
    struct VTSQUISH* pvtsquish;
    struct VTFRZG* pvtfrzg;
    struct VTBONE* pvtbone;
    struct VTLBONE* pvtlbone;
    struct VTMAP* pvtmap;
    struct VTVISMAP* pvtvismap;
    struct VT_VISZONE* pvt_viszone;
    struct VTASEG* pvtaseg;
    struct VTASEGA* pvtasega;
    struct VTASEGBL* pvtasegbl;
    struct VTSM* pvtsm;
    struct VTSMA* pvtsma;
    struct VTIKH* pvtikh;
    struct VTLIKH* pvtlikh;
    struct VTSCH* pvtsch;
    struct VTRIPG* pvtripg;
    struct VTBLIPG* pvtblipg;
    struct VTEMITTER* pvtemitter;
    struct VTEXPL* pvtexpl;
    struct VTEXPLG* pvtexplg;
    struct VTEXPLO* pvtexplo;
    struct VTEXPLS* pvtexpls;
    struct VTPROXY* pvtproxy;
    struct VTDIALOG* pvtdialog;
    struct VTHSHAPE* pvthshape;
    struct VTHPNT* pvthpnt;
    struct VTHBSK* pvthbsk;
    struct VTRCHM* pvtrchm;
    struct VTSTEP* pvtstep;
    struct VTSPRIZE* pvtsprize;
    struct VTSCPRIZE* pvtscprize;
    struct VTCLUE* pvtclue;
    struct VTLIFETKN* pvtlifetkn;
    struct VTLOCK* pvtlock;
    struct VTLOCKG* pvtlockg;
    struct VTVAULT* pvtvault;
    struct VTALBRK* pvtalbrk;
    struct VTALARM* pvtalarm;
    struct VTSENSOR* pvtsensor;
    struct VTLASEN* pvtlasen;
    struct VTCAMSEN* pvtcamsen;
    struct VTPRSEN* pvtprsen;
    struct VTTARGET* pvttarget;
    struct VTHND* pvthnd;
    struct VTPIPE* pvtpipe;
    struct VTBARRIER* pvtbarrier;
    struct VTTAIL* pvttail;
    struct VTJSG* pvtjsg;
    struct VTJT* pvtjt;
    struct VTJMT* pvtjmt;
    struct VTSGG* pvtsgg;
    struct VTSTEPGUARD* pvtstepguard;
    struct VTGOMER* pvtgomer;
    struct VTSMARTGUARD* pvtsmartguard;
    struct VTTZP* pvttzp;
    struct VTVOLZP* pvtvolzp;
    struct VTVOL* pvtvol;
    struct VTCHKPNT* pvtchkpnt;
    struct VTPATHZONE* pvtpathzone;
    struct VTBOMB* pvtbomb;
    struct VTCAN* pvtcan;
    struct VTSKY* pvtsky;
    struct VTFLY* pvtfly;
    struct VTDPRIZE* pvtdprize;
    struct VTCOIN* pvtcoin;
    struct VTCHARM* pvtcharm;
    struct VTKEY* pvtkey;
    struct VTGOLD* pvtgold;
    struct VTRATHOLE* pvtrathole;
    struct VTRAT* pvtrat;
    struct VTROB* pvtrob;
    struct VTROV* pvtrov;
    struct VTROH* pvtroh;
    struct VTROC* pvtroc;
    struct VTROST* pvtrost;
    struct VTROP* pvtrop;
    struct VTDART* pvtdart;
    struct VTDARTGUN* pvtdartgun;
    struct VTFLASH* pvtflash;
    struct VTMISSILE* pvtmissile;
    struct VTACCMISS* pvtaccmiss;
    struct VTTARMISS* pvttarmiss;
    struct VTSPLMISS* pvtsplmiss;
    struct VTGROUNDMISS* pvtgroundmiss;
    struct VTRWM* pvtrwm;
    struct VTCNVO* pvtcnvo;
    struct VTDYSH* pvtdysh;
    struct VTDSP* pvtdsp;
    struct VTWAYPOINT* pvtwaypoint;
    struct VTUBV* pvtubv;
    struct VTUBP* pvtubp;
    struct VTUBG* pvtubg;
    struct VTMBG* pvtmbg;
    struct VTSCENTMAP* pvtscentmap;
    struct VTBHG* pvtbhg;
    struct VTJLOC* pvtjloc;
    struct VTJLOVOL* pvtjlovol;
    struct VTJLO* pvtjlo;
    struct VTSPIRE* pvtspire;
    struct VTRAIL* pvtrail;
    struct VTLANDING* pvtlanding;
    struct VTROPE* pvtrope;
    struct VTWR* pvtwr;
    struct VTTANK* pvttank;
    struct VTTURRET* pvtturret;
    struct VTMURRAY* pvtmurray;
    struct VTPUFFER* pvtpuffer;
    struct VTPUFFC* pvtpuffc;
    struct VTPUFFB* pvtpuffb;
    struct VTPUFFT* pvtpufft;
    struct VTPUFFV* pvtpuffv;
    struct VTMRKV* pvtmrkv;
    struct VTCRFOD* pvtcrfod;
    struct VTCRFODB* pvtcrfodb;
    struct VTCRFODK* pvtcrfodk;
    struct VTCRBRAIN* pvtcrbrain;
    struct VTMGV* pvtmgv;
    struct VTMGC* pvtmgc;
    struct VTSUV* pvtsuv;
    struct VTJP* pvtjp;
    struct VTCYCLE* pvtcycle;
    struct VTHG* pvthg;
    struct VTMECHA* pvtmecha;
    struct VTSWP* pvtswp;
    struct VTLGN* pvtlgn;
    struct VTLGNB* pvtlgnb;
    struct VTJACK* pvtjack;
    struct VTJACKB* pvtjackb;
    struct VTJACKN* pvtjackn;
    struct VTJACKF* pvtjackf;
    struct VTMS* pvtms;
    struct VTSPEAKER* pvtspeaker;
    struct VTWM* pvtwm;
    struct VTSW* pvtsw;
    struct VTCM* pvtcm;
	struct CSidebag* psidebag;
};

enum class CID : int // Character ID ?
{
    Nil = -1,
    BASIC = 0,
    LO = 1,
    ALO = 2,
    SO = 3,
    MS = 4,
    PO = 5,
    STEP = 6,
    JT = 7,
    STEPGUARD = 8,
    SMARTGUARD = 9,
    GOMER = 10,
    UBG = 11,
    MBG = 12,
    BHG = 13,
    MURRAY = 14,
    PUFFC = 15,
    CRFOD = 16,
    CRFODB = 17,
    CRFODK = 18,
    TANK = 19,
    JP = 20,
    HG = 21,
    MECHA = 22,
    ROV = 23,
    TURRET = 24,
    VAULT = 25,
    PUFFER = 26,
    MGV = 27,
    SUV = 28,
    CYCLE = 29,
    LGN = 30,
    JACK = 31,
    RIPG = 32,
    WATER = 33,
    BRK = 34,
    BREAK = 35,
    ALBRK = 36,
    CAN = 37,
    DARTGUN = 38,
    SWP = 39,
    FRAGILE = 40,
    ZAPBREAK = 41,
    BRKP = 42,
    BUTTON = 43,
    VOLBTN = 44,
    JLOVOL = 45,
    SQUISH = 46,
    BONE = 47,
    SPRIZE = 48,
    SCPRIZE = 49,
    LIFETKN = 50,
    CLUE = 51,
    ALARM = 52,
    SENSOR = 53,
    LASEN = 54,
    CAMSEN = 55,
    PRSEN = 56,
    BARRIER = 57,
    IKH = 58,
    TZP = 59,
    VOLZP = 60,
    CNVO = 61,
    HBSK = 62,
    BOMB = 63,
    MISSILE = 64,
    ACCMISS = 65,
    TARMISS = 66,
    SPLMISS = 67,
    GROUNDMISS = 68,
    FLY = 69,
    RAT = 70,
    ROH = 71,
    ROC = 72,
    ROST = 73,
    ROP = 74,
    DART = 75,
    UBV = 76,
    UBP = 77,
    DSP = 78,
    JLO = 79,
    PUFFT = 80,
    MRKV = 81,
    LGNB = 82,
    BLIPG = 83,
    CAMERA = 84,
    LBONE = 85,
    EMITTER = 86,
    LIGHT = 87,
    SCH = 88,
    LIKH = 89,
    CHKPNT = 90,
    PROXY = 91,
    SKY = 92,
    DPRIZE = 93,
    CHARM = 94,
    COIN = 95,
    KEY = 96,
    GOLD = 97,
    LOCK = 98,
    LOCKG = 99,
    TAIL = 100,
    ROB = 101,
    FLASH = 102,
    DYSH = 103,
    SCENTMAP = 104,
    WAYPOINT = 105,
    TN = 106,
    JLOC = 107,
    DIALOG = 108,
    SPEAKER = 109,
    ROPE = 110,
    WM = 111,
    PUFFB = 112,
    CRBRAIN = 113,
    MGC = 114,
    JACKB = 115,
    JACKN = 116,
    JACKF = 117,
    SW = 118,
    CM = 119,
    SHAPE = 120,
    HSHAPE = 121,
    PIPE = 122,
    RAIL = 123,
    LANDING = 124,
    XFM = 125,
    WARP = 126,
    TARGET = 127,
    HND = 128,
    EXPL = 129,
    EXPLG = 130,
    EXPLO = 131,
    EXPLS = 132,
    VOL = 133,
    RATHOLE = 134,
    PUFFV = 135,
    EXIT = 136,
    PNT = 137,
    PNTSV = 138,
    PNTS = 139,
    PNTVEC = 140,
    HPNT = 141,
    JMT = 142,
    SPIRE = 143,
    SCAN = 144,
    ASEG = 145,
    ASEGBL = 146,
    MAP = 147,
    VISZONE = 148,
    VISMAP = 149,
    FRZG = 150,
    SM = 151,
    SGG = 152,
    PATHZONE = 153,
    RCHM = 154,
    RWM = 155,
    WR = 156,
    KEYHOLE = 157,
    JSG = 158,
    ASEGA = 159,
    SMA = 160,
    FCST = 161,
    Max = 162
};

struct VT {
    VT* pvtSuper;
    CID cid;
    int grfcid;
    int cb;
};

struct VTBASIC {
    struct VT* pvtSuper = nullptr;
    CID cid = CID::BASIC;
};

extern VTBASIC g_vtbasic;