#pragma once
#include <step.h>
#include <iostream>


struct VTJT {
    struct VT* pvtSuper = g_vtstep.pvtSuper;
    enum CID cid = CID::JT;
    int grfcid = 11;
    int cb = 0x2730;
    /*undefined1* pfnInitJt;
    undefined1* pfnSetLoDefaults;
    undefined1* pfnAddLo;
    undefined1* pfnRemoveLo;
    undefined1* pfnAddAloHierarchy;
    undefined1* pfnRemoveAloHierarchy;
    undefined1* pfnOnPoAdd;
    undefined1* pfnOnPoRemove;
    undefined1* pfnCloneAloHierarchy;
    undefined1* pfnClonePo;
    undefined1* pfnLoadJtFromBrx;
    undefined1* pfnAddLoRecursive;
    undefined1* pfnRemoveLoRecursive;
    undefined1* pfnHandleJtMessage;
    undefined1* pfnSendSoMessage;
    undefined1* pfnBindAlo;
    undefined1* pfnPostJtLoad;
    undefined1* pfnUpdateJt;
    undefined1* pfnUpdateStepXfWorld;
    undefined1* pfnUpdateSoXfWorldHierarchy;
    undefined1* pfnFreezeSo;
    undefined1* pfnSetSoParent;
    undefined1* pfnApplySoProxy;
    undefined1* pfnSubscribeLoObject;
    undefined1* pfnUnsubscribeLoObject;
    undefined1* pfnSubscribeLoStruct;
    undefined1* pfnUnsubscribeLoStruct;
    undefined1* pfnGetStepParams;
    undefined1* pfnUpdateLoLiveEdit;
    undefined1* pfnProjectJtTransform;
    undefined1* pfnPresetJtAccel;
    undefined1* pfnTranslateSoToPos;
    undefined1* pfnRotateStepToMat;
    undefined1* pfnMatchAloOtherObject;
    undefined1* pfnSetSoVelocityVec;
    undefined1* pfnSetSoAngularVelocityVec;
    undefined1* pfnPredictStepPosition;
    undefined1* pfnPredictStepRotation;
    undefined1* pfnRenderJtAll;
    undefined1* pfnRenderJtSelf;
    undefined1* pfnRenderAloGlobset;
    undefined1* pfnUpdateAloInfluences;
    undefined1* pfnAdjustAloPosition;
    undefined1* pfnAdjustAloRotation;
    undefined1* pfnUnadjustAloRotation;
    undefined1* pfnRecacheAloActList;
    undefined1* pfnUpdateAloConstraints;
    undefined1* pfnFAbsorbSoWkr;
    undefined1* pfnDisplaceSo;
    undefined1* pfnImpactSo;
    undefined1* pfnPivotSo;
    undefined1* pfnUpdateJtBounds;
    undefined1* pfnAddJtExternalAccelerations;
    undefined1* pfnCloneStepPhys;
    undefined1* pfnRenumberSo;
    undefined1* pfnPropagateStepForce;
    undefined1* pfnDistributeSoEffects;
    undefined1* pfnFIgnoreSoIntersection;
    undefined1* pfnAddSoXps;
    undefined1* pfnAddJtCustomXps;
    undefined1* pfnAdjustSoXpLocal;
    undefined1* pfnAdjustJtNewXp;
    undefined1* pfnAdjustJtXpVelocity;
    undefined1* pfnAdjustJtDz;
    undefined1* pfnAdjustJtXps;
    undefined1* pfnUpdateJtInternalXps;
    undefined1* pfnNotifySoImpact;
    undefined1* pfnUpdateSoPivots;
    undefined1* pfnUpdateSoImpacts;
    undefined1* pfnUpdateJtPosWorldPrev;
    undefined1* pfnGetJtCpdefi;
    undefined1* pfnAddJtWaterAcceleration;
    undefined1* pfnFInflictSoZap;
    undefined1* pfnOnPoActive;
    undefined1* pfnUpdateJtActive;
    undefined1* pfnSetPoPlayable;
    undefined1* pfnFIsJtSoundBase;
    undefined1* pfnFInvulnerableJt;
    undefined1* pfnFTakeJtDamage;
    undefined1* pfnJthsCurrentJt;
    undefined1* pfnCollectJtPrize;
    undefined1* pfnUseJtCharm;
    undefined1* pfnGetJtDiapi;
    undefined1* pfnPlayJtDialog;
    undefined1* pfnUpdateStepMatTarget;
    undefined1* pfnCtTorqueJt;
    undefined1* pfnFCheckJtXpBase;*/
};

extern VTJT g_vtjt;