#pragma once
#include <step.h>

struct STEPGUARD {
    struct STEP STEPGUARD;
    struct SGG* psgg;
    enum SGS sgs;
    float tSgs;
    int grfsgsc;
    enum SGS sgsNext;
    struct ALO* paloHead;
    struct LM lmAttackS;
    struct LM lmAttackT;
    float tAttackNext;
    float radAttackMax;
    struct ASEG* pasegPatrol;
    struct ASEGA* pasegaPatrol;
    //struct SGA mpsgssga[17];
    struct ASEGA* pasegaSgs;
    int csgmap;
    //struct SGMAP asgmap[8];
    struct ASEG* pasegPrev;
    float uAsegaPrev;
    //struct SGP mpsgssgp[17];
    struct SO* psoPhysDefault;
    struct VECTOR posSearch;
    float radTargetSearch;
    float tPatrolReturn;
    float tPatrolPrev;
    float svtPatrolPrev;
    enum RPK rpk;
    enum OID oidPathzone;
    struct PATHZONE* ppathzone;
    int cposPath;
    int iposPath;
    struct VECTOR aposPath[16];
    struct VECTOR posGoal;
    struct VECTOR posGoalPath;
    int fPathValid;
    float tPathValid;
    int cStun;
    int fTumbleStun;
    float dtFade;
    struct WAYPOINT* pwaypoint;
    int csge;
    //struct SGE asge[4];
    struct XP* pxpEffect;
    struct VECTOR vThrow;
    int csgda;
    //struct SGDA asgda[4];
    int fExplExplicit;
    enum OID oidExpl;
    struct EXPL* pexpl;
    int fRwmExplicit;
    enum OID oidRwm;
    struct RWM* prwm;
    int ichkDead;
    int fFirstFrame;
    float uIdleStart;
    int fFlying;
    float dzFlying;
    float radTilt;
    struct CLQ clqSToUPursue;
    int fEnemyExternal;
    int fRebindEnemy;
    struct SO* psoEnemyExternal;
    enum OID oidEnemyExternal;
    struct SO* psoSubscribe;
    int ccoin;
    struct STEPGUARD* pstepguardBase;
    int fAnimatedJump;
    int fLockHeading;
    int fLockHeadingExternal;
    int fLockState;
    int fExternalAI;
    int fFreefall;
    int fFreefallAseg;
    float dxFreefall;
    float dtFreefall;
    struct LM lmRDtFreefall;
    float tFreefallLand;
    struct VECTOR posFreefallLand;
    struct VECTOR vFreefallLand;
    float uFling;
    int fAutoFadeDying;
    float tGiveUpSearch;
    float tStopPatrol;
    float tTaunt;
    float tLostPlayer;
};

struct VTSTEPGUARD {
    struct VT* pvtSuper = g_vtstep.pvtSuper;
    enum CID cid = CID::STEPGUARD;
    int grfcid = 11;
    int cb = 0xB90;
    /*undefined1* pfnInitStepguard;
    undefined1* pfnSetLoDefaults;
    undefined1* pfnAddLo;
    undefined1* pfnRemoveLo;
    undefined1* pfnAddAloHierarchy;
    undefined1* pfnRemoveAloHierarchy;
    undefined1* pfnOnStepguardAdd;
    undefined1* pfnOnStepguardRemove;
    undefined1* pfnCloneAloHierarchy;
    undefined1* pfnCloneStepguard;
    undefined1* pfnLoadStepguardFromBrx;
    undefined1* pfnAddLoRecursive;
    undefined1* pfnRemoveLoRecursive;
    undefined1* pfnHandleStepguardMessage;
    undefined1* pfnSendSoMessage;
    undefined1* pfnBindStepguard;
    undefined1* pfnPostStepguardLoad;
    undefined1* pfnUpdateStepguard;
    undefined1* pfnUpdateStepXfWorld;
    undefined1* pfnUpdateSoXfWorldHierarchy;
    undefined1* pfnFreezeSo;
    undefined1* pfnSetSoParent;
    undefined1* pfnApplySoProxy;
    undefined1* pfnSubscribeLoObject;
    undefined1* pfnUnsubscribeLoObject;
    undefined1* pfnSubscribeLoStruct;
    undefined1* pfnUnsubscribeLoStruct;
    undefined1* pfnGetStepParams;
    undefined1* pfnUpdateLoLiveEdit;
    undefined1* pfnProjectSoTransform;
    undefined1* pfnPresetStepguardAccel;
    undefined1* pfnTranslateSoToPos;
    undefined1* pfnRotateStepToMat;
    undefined1* pfnMatchAloOtherObject;
    undefined1* pfnSetSoVelocityVec;
    undefined1* pfnSetSoAngularVelocityVec;
    undefined1* pfnPredictStepPosition;
    undefined1* pfnPredictStepRotation;
    undefined1* pfnRenderAloAll;
    undefined1* pfnRenderStepguardSelf;
    undefined1* pfnRenderAloGlobset;
    undefined1* pfnUpdateAloInfluences;
    undefined1* pfnAdjustAloPosition;
    undefined1* pfnAdjustAloRotation;
    undefined1* pfnUnadjustAloRotation;
    undefined1* pfnRecacheAloActList;
    undefined1* pfnUpdateAloConstraints;
    undefined1* pfnFAbsorbStepguardWkr;
    undefined1* pfnDisplaceSo;
    undefined1* pfnImpactSo;
    undefined1* pfnPivotSo;
    undefined1* pfnUpdateSoBounds;
    undefined1* pfnAddSoExternalAccelerations;
    undefined1* pfnCloneStepPhys;
    undefined1* pfnRenumberSo;
    undefined1* pfnPropagateStepForce;
    undefined1* pfnDistributeSoEffects;
    undefined1* pfnFIgnoreStepguardIntersection;
    undefined1* pfnAddSoXps;
    undefined1* pfnAddStepguardCustomXps;
    undefined1* pfnAdjustSoXpLocal;
    undefined1* pfnAdjustStepguardNewXp;
    undefined1* pfnAdjustStepXpVelocity;
    undefined1* pfnAdjustStepguardDz;
    undefined1* pfnAdjustStepXps;
    undefined1* pfnUpdateSoInternalXps;
    undefined1* pfnNotifySoImpact;
    undefined1* pfnUpdateSoPivots;
    undefined1* pfnUpdateSoImpacts;
    undefined1* pfnUpdateSoPosWorldPrev;
    undefined1* pfnGetPoCpdefi;
    undefined1* pfnAddSoWaterAcceleration;
    undefined1* pfnFInflictStepguardZap;
    undefined1* pfnOnPoActive;
    undefined1* pfnUpdatePoActive;
    undefined1* pfnSetPoPlayable;
    undefined1* pfnFIsPoSoundBase;
    undefined1* pfnFInvulnerablePo;
    undefined1* pfnFTakeStepguardDamage;
    undefined1* pfnJthsCurrentPo;
    undefined1* pfnCollectPoPrize;
    undefined1* pfnUsePoCharm;
    undefined1* pfnGetPoDiapi;
    undefined1* pfnPlayPoDialog;
    undefined1* pfnUpdateStepMatTarget;
    undefined1* pfnCtTorqueStep;
    undefined1* pfnFCheckStepXpBase;
    undefined1* pfnFDetectStepguard;
    undefined1* pfnSgasGetStepguard;
    undefined1* pfnSgsNextStepguardAI;
    undefined1* pfnUpdateStepguardSgs;
    undefined1* pfnOnStepguardExitingSgs;
    undefined1* pfnOnStepguardEnteringSgs;
    undefined1* pfnFCanStepguardAttack;
    undefined1* pfnUpdateStepguardGoal;
    undefined1* pfnDoStepguardFreefallLanding;
    undefined1* pfnDoStepguardFreefallJump;
    undefined1* pfnPsoEnemyStepguard;*/
};

extern VTSTEPGUARD g_vtstepguard;

struct VTSGG {
    struct VT* pvtSuper = g_vtlo.pvtSuper;
    enum CID cid = CID::SGG;
    int grfcid = 0;
    int cb = 0x190;
    /*undefined1* pfnInitSgg;
    undefined1* pfnSetLoDefaults;
    undefined1* pfnAddLo;
    undefined1* pfnRemoveLo;
    undefined1* pfnAddLoHierarchy;
    undefined1* pfnRemoveLoHierarchy;
    undefined1* pfnOnLoAdd;
    undefined1* pfnOnLoRemove;
    undefined1* pfnCloneLoHierarchy;
    undefined1* pfnCloneLo;
    undefined1* pfnLoadLoFromBrx;
    undefined1* pfnAddLoRecursive;
    undefined1* pfnRemoveLoRecursive;
    undefined1* pfnHandleLoMessage;
    undefined1* pfnSendLoMessage;
    undefined1* pfnBindSgg;
    undefined1* pfnPostLoLoad;
    undefined1* pfnUpdateLo;
    undefined1* pfnUpdateLoXfWorld;
    undefined1* pfnUpdateLoXfWorldHierarchy;
    undefined1* pfnFreezeLo;
    undefined1* pfnSetLoParent;
    undefined1* pfnApplyLoProxy;
    undefined1* pfnSubscribeLoObject;
    undefined1* pfnUnsubscribeLoObject;
    undefined1* pfnSubscribeLoStruct;
    undefined1* pfnUnsubscribeLoStruct;
    undefined1* pfnGetLoParams;
    undefined1* pfnUpdateLoLiveEdit;*/
};

extern VTSGG g_vtsgg;