#pragma once
#include <po.h>
#include <iostream>

struct VTSUV {
    struct VT* pvtSuper = g_vtpo.pvtSuper;
    enum CID cid = CID::SUV;
    int grfcid = 11;
    int cb = 0xBE0;
    /*undefined1* pfnInitSuv;
    undefined1* pfnSetLoDefaults;
    undefined1* pfnAddLo;
    undefined1* pfnRemoveLo;
    undefined1* pfnAddAloHierarchy;
    undefined1* pfnRemoveAloHierarchy;
    undefined1* pfnOnPoAdd;
    undefined1* pfnOnPoRemove;
    undefined1* pfnCloneAloHierarchy;
    undefined1* pfnClonePo;
    undefined1* pfnLoadSoFromBrx;
    undefined1* pfnAddLoRecursive;
    undefined1* pfnRemoveLoRecursive;
    undefined1* pfnHandleSuvMessage;
    undefined1* pfnSendSoMessage;
    undefined1* pfnBindAlo;
    undefined1* pfnPostSuvLoad;
    undefined1* pfnUpdateSuv;
    undefined1* pfnUpdateSuvXfWorld;
    undefined1* pfnUpdateSoXfWorldHierarchy;
    undefined1* pfnFreezeSo;
    undefined1* pfnSetSoParent;
    undefined1* pfnApplySoProxy;
    undefined1* pfnSubscribeLoObject;
    undefined1* pfnUnsubscribeLoObject;
    undefined1* pfnSubscribeLoStruct;
    undefined1* pfnUnsubscribeLoStruct;
    undefined1* pfnGetSoParams;
    undefined1* pfnUpdateLoLiveEdit;
    undefined1* pfnProjectSoTransform;
    undefined1* pfnPresetSuvAccel;
    undefined1* pfnTranslateSoToPos;
    undefined1* pfnRotateSoToMat;
    undefined1* pfnMatchAloOtherObject;
    undefined1* pfnSetSoVelocityVec;
    undefined1* pfnSetSoAngularVelocityVec;
    undefined1* pfnPredictAloPosition;
    undefined1* pfnPredictAloRotation;
    undefined1* pfnRenderAloAll;
    undefined1* pfnRenderSuvSelf;
    undefined1* pfnRenderAloGlobset;
    undefined1* pfnUpdateSuvInfluences;
    undefined1* pfnAdjustAloPosition;
    undefined1* pfnAdjustAloRotation;
    undefined1* pfnUnadjustAloRotation;
    undefined1* pfnRecacheAloActList;
    undefined1* pfnUpdateAloConstraints;
    undefined1* pfnFAbsorbSoWkr;
    undefined1* pfnDisplaceSo;
    undefined1* pfnImpactSo;
    undefined1* pfnPivotSo;
    undefined1* pfnUpdateSuvBounds;
    undefined1* pfnAddSoExternalAccelerations;
    undefined1* pfnCloneSoPhys;
    undefined1* pfnRenumberSo;
    undefined1* pfnPropagateSoForce;
    undefined1* pfnDistributeSoEffects;
    undefined1* pfnFIgnoreSoIntersection;
    undefined1* pfnAddSoXps;
    undefined1* pfnAddSuvCustomXps;
    undefined1* pfnAdjustSoXpLocal;
    undefined1* pfnAdjustSuvNewXp;
    undefined1* pfnAdjustSoXpVelocity;
    undefined1* pfnAdjustSoDz;
    undefined1* pfnAdjustSoXps;
    undefined1* pfnUpdateSuvInternalXps;
    undefined1* pfnNotifySoImpact;
    undefined1* pfnUpdateSoPivots;
    undefined1* pfnUpdateSoImpacts;
    undefined1* pfnUpdateSoPosWorldPrev;
    undefined1* pfnGetSuvCpdefi;
    undefined1* pfnAddSoWaterAcceleration;
    undefined1* pfnFInflictSoZap;
    undefined1* pfnOnSuvActive;
    undefined1* pfnUpdateSuvActive;
    undefined1* pfnSetPoPlayable;
    undefined1* pfnFIsPoSoundBase;
    undefined1* pfnFInvulnerablePo;
    undefined1* pfnFTakePoDamage;
    undefined1* pfnJthsCurrentPo;
    undefined1* pfnCollectSuvPrize;
    undefined1* pfnUsePoCharm;
    undefined1* pfnGetPoDiapi;
    undefined1* pfnPlayPoDialog;*/
};

extern VTSUV g_vtsuv;